### ISSUE TITLE
Gazebo package set the wrong GAZEBO_PLUGIN_PATH

### ISSUE THREAD

**Issue by khancyr** [ros-infrastructure/reprepro-updater#41] opened 2017-04-25 10:49 UTC
Hello,
I don't find where to submit a PR to correct this but the fix should be simple.
When installing gazebo with ROS repository (with something like sudo apt install ros-kinetic-desktop-full) we got a wrong GAZEBO_PLUGIN_PATH
In fact, in /usr/lib/x86_64-linux-gnu/cmake/gazebo/gazebo-config.cmake it is define has

```
    if (GAZEBO_CONFIG_INCLUDED)
      return()
    endif()
    set(GAZEBO_CONFIG_INCLUDED TRUE)
    set(GAZEBO_VERSION 7.0)
    set(GAZEBO_MAJOR_VERSION 7)
    
    set(GAZEBO_PLUGIN_PATH "/usr/lib/x86_64-linux-gnu/gazebo-7/plugins")
    
    # The media path contains the location on disk where images,
    # materials scripts, shaders, and other related resources are stored.
    set(GAZEBO_MEDIA_PATH "/usr/share/gazebo-7/media")
    
    set(GAZEBO_PLUGIN_PATH "/usr/lib/x86_64-linux-gnu/gazebo-7.0/plugins")
    
    # The media path contains the location on disk where images,
    # materials scripts, shaders, and other related resources are stored.
    set(GAZEBO_MEDIA_PATH "/usr/share/gazebo-7.0/media")

```
We can see that GAZEBO_PLUGIN_PATH is set twice and the second time wrongly as there is nothing in /usr/lib/x86_64-linux-gnu/gazebo-7.0/plugins. But building new plugin will put them in this directory that is wrong...

If we look at the package from OSRF ( following http://gazebosim.org/tutorials?tut=install_ubuntu ) , the GAZEBO_PLUGIN_PATH is well set : 

  ```
  if (GAZEBO_CONFIG_INCLUDED)
      return()
    endif()
    set(GAZEBO_CONFIG_INCLUDED TRUE)
    set(GAZEBO_VERSION 7.6)
    set(GAZEBO_MAJOR_VERSION 7)
    
    set(GAZEBO_PLUGIN_PATH "/usr/lib/x86_64-linux-gnu/gazebo-7/plugins")
    
    # The media path contains the location on disk where images,
    # materials scripts, shaders, and other related resources are stored.
    set(GAZEBO_MEDIA_PATH "/usr/share/gazebo-7/media")
```

**Comment by dirk-thomas** [comment] 2017-04-25 15:24
@j-rivero FYI

**Comment by j-rivero** [comment] 2017-04-25 18:02
Thanks. Let's continue it in https://bitbucket.org/osrf/gazebo/issues/2258/gazebo-deb-for-ros-has-wrong. I don't think that the problem has anything to do with this repo.

**Comment by khancyr** [comment] 2017-04-25 18:08
@j-rivero Ok!
Sorry for the spam here and on gazebo side, I would have happily try to help but I didn't find where gazebo package for ROS was build !

**Comment by tfoote** [comment] 2017-04-25 18:09
@khancyr This is a good place since this is where we manage importing packages from upstream. 

@j-rivero is this just a matter of importing a newer version from packages.osrfoundation.org?

**Comment by j-rivero** [comment] 2017-04-25 18:15
> @j-rivero is this just a matter of importing a newer version from packages.osrfoundation.org?

I was exploring when the fix was released and it seems like gazebo 7.3.0 is the first version when the problem fixed. 

We could import that version or any other recent version of gazebo7 (this will bring the latest fixes and features to ROS) but the best way to minimize potential regressions on the ROS side would be to use packaging to add a patch to solve this particular issue on top of current gazebo 7.0.0, increase the release number and create new debs for the ROS repository.

**Comment by khancyr** [comment] 2017-04-27 13:45
I would vote to go to lastest gazebo7 but I don't know you releases work here.

**Comment by j-rivero** [comment] 2017-04-27 16:27
> I would vote to go to lastest gazebo7 but I don't know you releases work here.

Given that we have a path to be able to use the latest gazebo7 version with ROS (just add the packages.osrfoundation.org repository to the ROS one and update your gazebo packages) I'm more in favor of stability (at all levels) in this case. I will build new gazebo 7.0.0 packages with the patch.

**Comment by tfoote** [comment] 2018-01-02 22:46
I believe that this has been resolved in the gazebo packaging by now. Closing here.

**Closed by tfoote** 2018-01-02 22:46 UTC

**Comment by patrickelectric** [comment] 2018-07-12 18:01
I did a fresh install from ubuntu 16.04 today and got the same problem.

**Comment by tfoote** [comment] 2018-07-12 22:31
Please report this on the repository from which the plugin is coming from. Or ask an question on answers.gazebosim.org  Commenting on an old closed ticket is not a place that will get much attention.
